"""add spare parts crud

Revision ID: 36e1381c5069
Revises: 97b4b0154ab6
Create Date: 2025-06-01 07:42:03.393632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e1381c5069'
down_revision: Union[str, None] = '97b4b0154ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('alias_name', sa.String(length=255), nullable=True),
    sa.Column('sparePartType', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['sparePartType'], ['spare_part_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spare_part')
    # ### end Alembic commands ###
