"""add factory parts relationship to factoryparts

Revision ID: 40d78f75fd7c
Revises: 502e5ab24846
Create Date: 2025-05-27 10:22:08.931611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d78f75fd7c'
down_revision: Union[str, None] = '502e5ab24846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema using batch mode (for SQLite support)."""
    with op.batch_alter_table("machine_catalogs", schema=None) as batch_op:
        batch_op.add_column(sa.Column('factory_parts_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_machine_catalogs_factory_parts_id",
            referent_table='factory_parts',
            local_cols=['factory_parts_id'],
            remote_cols=['id']
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machine_catalogs', type_='foreignkey')
    op.drop_column('machine_catalogs', 'factory_parts_id')
    # ### end Alembic commands ###
