"""fix machine catalog factory part

Revision ID: 502e5ab24846
Revises: 7305bfb18dcf
Create Date: 2025-05-27 10:21:33.797681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502e5ab24846'
down_revision: Union[str, None] = '7305bfb18dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine_catalogs', 'factory_part_id')
    op.drop_column('machine_catalogs', 'factory_parts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_catalogs', sa.Column('factory_parts_id', sa.INTEGER(), nullable=True))
    op.add_column('machine_catalogs', sa.Column('factory_part_id', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
