"""remove something

Revision ID: 52e26fa0c5d3
Revises: f2277df39bed
Create Date: 2025-06-03 09:30:22.574849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e26fa0c5d3'
down_revision: Union[str, None] = 'f2277df39bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spare_part_properties', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spare_part_properties', sa.Column('value', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
