"""add location table

Revision ID: 6d9fde3aca26
Revises: 40d78f75fd7c
Create Date: 2025-05-28 07:56:13.685146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9fde3aca26'
down_revision: Union[str, None] = '40d78f75fd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.String(length=15), nullable=True),
    sa.Column('y', sa.String(length=15), nullable=True),
    sa.Column('z', sa.String(length=15), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###
