"""add machine catalogs

Revision ID: 7305bfb18dcf
Revises: ba546686c784
Create Date: 2025-05-27 10:01:03.660116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7305bfb18dcf'
down_revision: Union[str, None] = 'ba546686c784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(length=256), nullable=False),
    sa.Column('location_in_factory', sa.String(length=256), nullable=True),
    sa.Column('factory_part_id', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('is_tool', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_catalogs')
    # ### end Alembic commands ###
