"""init db

Revision ID: 94b73bddf5c2
Revises: 
Create Date: 2025-06-03 11:13:37.217520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b73bddf5c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contactEmail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['factory_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.String(length=15), nullable=True),
    sa.Column('y', sa.String(length=15), nullable=True),
    sa.Column('z', sa.String(length=15), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spare_part_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_of_measure_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(length=256), nullable=False),
    sa.Column('location_in_factory', sa.String(length=256), nullable=True),
    sa.Column('factory_parts_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('is_tool', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['factory_parts_id'], ['factory_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spare_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('alias_name', sa.String(length=255), nullable=True),
    sa.Column('spare_part_type_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['spare_part_type_id'], ['spare_part_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_of_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('unit_in_group', sa.Float(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['unit_of_measure_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('value_type', sa.Enum('INTEGER', 'STRING', 'BOOLEAN', 'FLOAT', name='propertyvaluetype'), nullable=True),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spare_part_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spare_part_type_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['spare_part_type_id'], ['spare_part_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spare_part_properties')
    op.drop_table('property')
    op.drop_table('unit_of_measure')
    op.drop_table('spare_part')
    op.drop_table('machine_catalogs')
    op.drop_table('unit_of_measure_group')
    op.drop_table('tag')
    op.drop_table('spare_part_type')
    op.drop_table('location')
    op.drop_table('factory_parts')
    op.drop_table('company')
    # ### end Alembic commands ###
