"""Add Company table

Revision ID: ba546686c784
Revises: f8e56d97bf6e
Create Date: 2025-05-26 09:04:15.601357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba546686c784'
down_revision: Union[str, None] = 'f8e56d97bf6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('contactEmail')
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactEmail', sa.String(length=255), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'contactEmail',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('company', 'website',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
